#lang s-exp scimitar/ir

(require scimitar/ty)
(provide example)

(forall (
  truck-mega-rig-cost     ; 0.33
  truck-mega-rig-cap      ; 2000
  truck-the-monster-cost  ; 0.32
  truck-the-monster-cap   ; 2000
  truck-big-bertha-cost   ; 0.30
  truck-big-bertha-cap    ; 1800
  truck-keep-truckin-cost ; 0.25
  truck-keep-truckin-cap  ; 1400
  truck-lonely-road-cost  ; 0.20
  truck-lonely-road-cap   ; 600
  truck-dusty-trail-cost  ; 0.19
  truck-dusty-trail-cap   ; 600
  truck-little-guy-cost   ; 0.16
  truck-little-guy-cap    ; 300
  truck-putt-putt-cost    ; 0.15
  truck-putt-putt-cap     ; 300

  road-smallville-mediumville-len    ; 40
  road-smallville-mediumville-cost   ; 20
  road-mediumville-smallville-len    ; 40
  road-mediumville-smallville-cost   ; 20
  road-smallville-bigville-len       ; 60
  road-smallville-bigville-cost      ; 10
  road-bigville-smallville-len       ; 60
  road-bigville-smallville-cost      ; 10
  road-mediumville-bigville-len      ; 30
  road-mediumville-bigville-cost     ; 40
  road-bigville-mediumville-len      ; 30
  road-bigville-mediumville-cost     ; 40
  road-nowheresville-smallville-len  ; 100
  road-nowheresville-smallville-cost ; 0
  road-smallville-nowheresville-len  ; 100
  road-smallville-nowheresville-cost ; 0

  product-apples-size         ; 3
  product-apples-profit       ; 0.50
  product-banana-size         ; 2
  product-banana-profit       ; 0.25
  product-orange-size         ; 4
  product-orange-profit       ; 0.75
  product-grapes-size         ; 2
  product-grapes-profit       ; 1.25

  city-smallville-cost        ; 1000
  city-smallville-capacity    ; 14000
  city-smallville-apples      ; 400
  city-smallville-banana      ; 0
  city-smallville-orange      ; 600
  city-smallville-grapes      ; 50

  city-mediumville-cost       ; 1200
  city-mediumville-capacity   ; 22000
  city-mediumville-apples     ; 1750
  city-mediumville-banana     ; 500
  city-mediumville-orange     ; 3000
  city-mediumville-grapes     ; 2000

  city-bigville-cost          ; 900
  city-bigville-capacity      ; 40000
  city-bigville-apples        ; 4000
  city-bigville-banana        ; 5500
  city-bigville-orange        ; 5500
  city-bigville-grapes        ; 4000

  city-nowheresville-cost     ; 100
  city-nowheresville-capacity ; 15000
  city-nowheresville-apples   ; 50
  city-nowheresville-banana   ; 0
  city-nowheresville-orange   ; 40
  city-nowheresville-grapes   ; 0
  )
  (define
    (example () (: profit (realty)))
    (locals
      (: mega-rig-takes-any-road (bitty))
      (: the-monster-takes-any-road (bitty))
      (: big-bertha-takes-any-road (bitty))
      (: keep-truckin-takes-any-road (bitty))
      (: lonely-road-takes-any-road (bitty))
      (: dusty-trail-takes-any-road (bitty))
      (: little-guy-takes-any-road (bitty))
      (: putt-putt-takes-any-road (bitty))

      (: mega-rig-takes-sma-med (bitty))
      (: mega-rig-takes-med-sma (bitty))
      (: mega-rig-takes-sma-big (bitty))
      (: mega-rig-takes-big-sma (bitty))
      (: mega-rig-takes-med-big (bitty))
      (: mega-rig-takes-big-med (bitty))
      (: mega-rig-takes-now-sma (bitty))
      (: mega-rig-takes-sma-now (bitty))
      (: the-monster-takes-sma-med (bitty))
      (: the-monster-takes-med-sma (bitty))
      (: the-monster-takes-sma-big (bitty))
      (: the-monster-takes-big-sma (bitty))
      (: the-monster-takes-med-big (bitty))
      (: the-monster-takes-big-med (bitty))
      (: the-monster-takes-now-sma (bitty))
      (: the-monster-takes-sma-now (bitty))
      (: big-bertha-takes-sma-med (bitty))
      (: big-bertha-takes-med-sma (bitty))
      (: big-bertha-takes-sma-big (bitty))
      (: big-bertha-takes-big-sma (bitty))
      (: big-bertha-takes-med-big (bitty))
      (: big-bertha-takes-big-med (bitty))
      (: big-bertha-takes-now-sma (bitty))
      (: big-bertha-takes-sma-now (bitty))
      (: keep-truckin-takes-sma-med (bitty))
      (: keep-truckin-takes-med-sma (bitty))
      (: keep-truckin-takes-sma-big (bitty))
      (: keep-truckin-takes-big-sma (bitty))
      (: keep-truckin-takes-med-big (bitty))
      (: keep-truckin-takes-big-med (bitty))
      (: keep-truckin-takes-now-sma (bitty))
      (: keep-truckin-takes-sma-now (bitty))
      (: lonely-road-takes-sma-med (bitty))
      (: lonely-road-takes-med-sma (bitty))
      (: lonely-road-takes-sma-big (bitty))
      (: lonely-road-takes-big-sma (bitty))
      (: lonely-road-takes-med-big (bitty))
      (: lonely-road-takes-big-med (bitty))
      (: lonely-road-takes-now-sma (bitty))
      (: lonely-road-takes-sma-now (bitty))
      (: dusty-trail-takes-sma-med (bitty))
      (: dusty-trail-takes-med-sma (bitty))
      (: dusty-trail-takes-sma-big (bitty))
      (: dusty-trail-takes-big-sma (bitty))
      (: dusty-trail-takes-med-big (bitty))
      (: dusty-trail-takes-big-med (bitty))
      (: dusty-trail-takes-now-sma (bitty))
      (: dusty-trail-takes-sma-now (bitty))
      (: little-guy-takes-sma-med (bitty))
      (: little-guy-takes-med-sma (bitty))
      (: little-guy-takes-sma-big (bitty))
      (: little-guy-takes-big-sma (bitty))
      (: little-guy-takes-med-big (bitty))
      (: little-guy-takes-big-med (bitty))
      (: little-guy-takes-now-sma (bitty))
      (: little-guy-takes-sma-now (bitty))
      (: putt-putt-takes-sma-med (bitty))
      (: putt-putt-takes-med-sma (bitty))
      (: putt-putt-takes-sma-big (bitty))
      (: putt-putt-takes-big-sma (bitty))
      (: putt-putt-takes-med-big (bitty))
      (: putt-putt-takes-big-med (bitty))
      (: putt-putt-takes-now-sma (bitty))
      (: putt-putt-takes-sma-now (bitty))

      (: mega-rig-sma-med-cost (nnegty))
      (: mega-rig-med-sma-cost (nnegty))
      (: mega-rig-sma-big-cost (nnegty))
      (: mega-rig-big-sma-cost (nnegty))
      (: mega-rig-med-big-cost (nnegty))
      (: mega-rig-big-med-cost (nnegty))
      (: mega-rig-now-sma-cost (nnegty))
      (: mega-rig-sma-now-cost (nnegty))
      (: the-monster-sma-med-cost (nnegty))
      (: the-monster-med-sma-cost (nnegty))
      (: the-monster-sma-big-cost (nnegty))
      (: the-monster-big-sma-cost (nnegty))
      (: the-monster-med-big-cost (nnegty))
      (: the-monster-big-med-cost (nnegty))
      (: the-monster-now-sma-cost (nnegty))
      (: the-monster-sma-now-cost (nnegty))
      (: big-bertha-sma-med-cost (nnegty))
      (: big-bertha-med-sma-cost (nnegty))
      (: big-bertha-sma-big-cost (nnegty))
      (: big-bertha-big-sma-cost (nnegty))
      (: big-bertha-med-big-cost (nnegty))
      (: big-bertha-big-med-cost (nnegty))
      (: big-bertha-now-sma-cost (nnegty))
      (: big-bertha-sma-now-cost (nnegty))
      (: keep-truckin-sma-med-cost (nnegty))
      (: keep-truckin-med-sma-cost (nnegty))
      (: keep-truckin-sma-big-cost (nnegty))
      (: keep-truckin-big-sma-cost (nnegty))
      (: keep-truckin-med-big-cost (nnegty))
      (: keep-truckin-big-med-cost (nnegty))
      (: keep-truckin-now-sma-cost (nnegty))
      (: keep-truckin-sma-now-cost (nnegty))
      (: lonely-road-sma-med-cost (nnegty))
      (: lonely-road-med-sma-cost (nnegty))
      (: lonely-road-sma-big-cost (nnegty))
      (: lonely-road-big-sma-cost (nnegty))
      (: lonely-road-med-big-cost (nnegty))
      (: lonely-road-big-med-cost (nnegty))
      (: lonely-road-now-sma-cost (nnegty))
      (: lonely-road-sma-now-cost (nnegty))
      (: dusty-trail-sma-med-cost (nnegty))
      (: dusty-trail-med-sma-cost (nnegty))
      (: dusty-trail-sma-big-cost (nnegty))
      (: dusty-trail-big-sma-cost (nnegty))
      (: dusty-trail-med-big-cost (nnegty))
      (: dusty-trail-big-med-cost (nnegty))
      (: dusty-trail-now-sma-cost (nnegty))
      (: dusty-trail-sma-now-cost (nnegty))
      (: little-guy-sma-med-cost (nnegty))
      (: little-guy-med-sma-cost (nnegty))
      (: little-guy-sma-big-cost (nnegty))
      (: little-guy-big-sma-cost (nnegty))
      (: little-guy-med-big-cost (nnegty))
      (: little-guy-big-med-cost (nnegty))
      (: little-guy-now-sma-cost (nnegty))
      (: little-guy-sma-now-cost (nnegty))
      (: putt-putt-sma-med-cost (nnegty))
      (: putt-putt-med-sma-cost (nnegty))
      (: putt-putt-sma-big-cost (nnegty))
      (: putt-putt-big-sma-cost (nnegty))
      (: putt-putt-med-big-cost (nnegty))
      (: putt-putt-big-med-cost (nnegty))
      (: putt-putt-now-sma-cost (nnegty))
      (: putt-putt-sma-now-cost (nnegty))

      (: mega-rig-cost (nnegty))
      (: the-monster-cost (nnegty))
      (: big-bertha-cost (nnegty))
      (: keep-truckin-cost (nnegty))
      (: lonely-road-cost (nnegty))
      (: dusty-trail-cost (nnegty))
      (: little-guy-cost (nnegty))
      (: putt-putt-cost (nnegty))

      (: sma-apples-would-stock (nnegty))
      (: sma-banana-would-stock (nnegty))
      (: sma-orange-would-stock (nnegty))
      (: sma-grapes-would-stock (nnegty))
      (: med-apples-would-stock (nnegty))
      (: med-banana-would-stock (nnegty))
      (: med-orange-would-stock (nnegty))
      (: med-grapes-would-stock (nnegty))
      (: big-apples-would-stock (nnegty))
      (: big-banana-would-stock (nnegty))
      (: big-orange-would-stock (nnegty))
      (: big-grapes-would-stock (nnegty))
      (: now-apples-would-stock (nnegty))
      (: now-banana-would-stock (nnegty))
      (: now-orange-would-stock (nnegty))
      (: now-grapes-would-stock (nnegty))

      (: sma-apples-stock (nnegty))
      (: sma-banana-stock (nnegty))
      (: sma-orange-stock (nnegty))
      (: sma-grapes-stock (nnegty))
      (: med-apples-stock (nnegty))
      (: med-banana-stock (nnegty))
      (: med-orange-stock (nnegty))
      (: med-grapes-stock (nnegty))
      (: big-apples-stock (nnegty))
      (: big-banana-stock (nnegty))
      (: big-orange-stock (nnegty))
      (: big-grapes-stock (nnegty))
      (: now-apples-stock (nnegty))
      (: now-banana-stock (nnegty))
      (: now-orange-stock (nnegty))
      (: now-grapes-stock (nnegty))

      (: sma-stock (nnegty))
      (: med-stock (nnegty))
      (: big-stock (nnegty))
      (: now-stock (nnegty))

      (: mega-rig-apples-would-stock (nnegty))
      (: mega-rig-banana-would-stock (nnegty))
      (: mega-rig-orange-would-stock (nnegty))
      (: mega-rig-grapes-would-stock (nnegty))
      (: the-monster-apples-would-stock (nnegty))
      (: the-monster-banana-would-stock (nnegty))
      (: the-monster-orange-would-stock (nnegty))
      (: the-monster-grapes-would-stock (nnegty))
      (: big-bertha-apples-would-stock (nnegty))
      (: big-bertha-banana-would-stock (nnegty))
      (: big-bertha-orange-would-stock (nnegty))
      (: big-bertha-grapes-would-stock (nnegty))
      (: keep-truckin-apples-would-stock (nnegty))
      (: keep-truckin-banana-would-stock (nnegty))
      (: keep-truckin-orange-would-stock (nnegty))
      (: keep-truckin-grapes-would-stock (nnegty))
      (: lonely-road-apples-would-stock (nnegty))
      (: lonely-road-banana-would-stock (nnegty))
      (: lonely-road-orange-would-stock (nnegty))
      (: lonely-road-grapes-would-stock (nnegty))
      (: dusty-trail-apples-would-stock (nnegty))
      (: dusty-trail-banana-would-stock (nnegty))
      (: dusty-trail-orange-would-stock (nnegty))
      (: dusty-trail-grapes-would-stock (nnegty))
      (: little-guy-apples-would-stock (nnegty))
      (: little-guy-banana-would-stock (nnegty))
      (: little-guy-orange-would-stock (nnegty))
      (: little-guy-grapes-would-stock (nnegty))
      (: putt-putt-apples-would-stock (nnegty))
      (: putt-putt-banana-would-stock (nnegty))
      (: putt-putt-orange-would-stock (nnegty))
      (: putt-putt-grapes-would-stock (nnegty))

      (: mega-rig-apples-stock (nnegty))
      (: mega-rig-banana-stock (nnegty))
      (: mega-rig-orange-stock (nnegty))
      (: mega-rig-grapes-stock (nnegty))
      (: the-monster-apples-stock (nnegty))
      (: the-monster-banana-stock (nnegty))
      (: the-monster-orange-stock (nnegty))
      (: the-monster-grapes-stock (nnegty))
      (: big-bertha-apples-stock (nnegty))
      (: big-bertha-banana-stock (nnegty))
      (: big-bertha-orange-stock (nnegty))
      (: big-bertha-grapes-stock (nnegty))
      (: keep-truckin-apples-stock (nnegty))
      (: keep-truckin-banana-stock (nnegty))
      (: keep-truckin-orange-stock (nnegty))
      (: keep-truckin-grapes-stock (nnegty))
      (: lonely-road-apples-stock (nnegty))
      (: lonely-road-banana-stock (nnegty))
      (: lonely-road-orange-stock (nnegty))
      (: lonely-road-grapes-stock (nnegty))
      (: dusty-trail-apples-stock (nnegty))
      (: dusty-trail-banana-stock (nnegty))
      (: dusty-trail-orange-stock (nnegty))
      (: dusty-trail-grapes-stock (nnegty))
      (: little-guy-apples-stock (nnegty))
      (: little-guy-banana-stock (nnegty))
      (: little-guy-orange-stock (nnegty))
      (: little-guy-grapes-stock (nnegty))
      (: putt-putt-apples-stock (nnegty))
      (: putt-putt-banana-stock (nnegty))
      (: putt-putt-orange-stock (nnegty))
      (: putt-putt-grapes-stock (nnegty))

      (: mega-rig-loading (nnegty))
      (: the-monster-loading (nnegty))
      (: big-bertha-loading (nnegty))
      (: keep-truckin-loading (nnegty))
      (: lonely-road-loading (nnegty))
      (: dusty-trail-loading (nnegty))
      (: little-guy-loading (nnegty))
      (: putt-putt-loading (nnegty))

      (: sma-apples-imports (realty))
      (: sma-banana-imports (realty))
      (: sma-orange-imports (realty))
      (: sma-grapes-imports (realty))
      (: med-apples-imports (realty))
      (: med-banana-imports (realty))
      (: med-orange-imports (realty))
      (: med-grapes-imports (realty))
      (: big-apples-imports (realty))
      (: big-banana-imports (realty))
      (: big-orange-imports (realty))
      (: big-grapes-imports (realty))
      (: now-apples-imports (realty))
      (: now-banana-imports (realty))
      (: now-orange-imports (realty))
      (: now-grapes-imports (realty))

      (: sma-apples-supply (realty))
      (: sma-banana-supply (realty))
      (: sma-orange-supply (realty))
      (: sma-grapes-supply (realty))
      (: med-apples-supply (realty))
      (: med-banana-supply (realty))
      (: med-orange-supply (realty))
      (: med-grapes-supply (realty))
      (: big-apples-supply (realty))
      (: big-banana-supply (realty))
      (: big-orange-supply (realty))
      (: big-grapes-supply (realty))
      (: now-apples-supply (realty))
      (: now-banana-supply (realty))
      (: now-orange-supply (realty))
      (: now-grapes-supply (realty))

      (: sma-cost (nnegty))
      (: med-cost (nnegty))
      (: big-cost (nnegty))
      (: now-cost (nnegty))

      (: sma-has-warehouse (bitty))
      (: med-has-warehouse (bitty))
      (: big-has-warehouse (bitty))
      (: now-has-warehouse (bitty))

      (: sma-profit (nnegty))
      (: med-profit (nnegty))
      (: big-profit (nnegty))
      (: now-profit (nnegty))
      )
    (>= 1 mega-rig-takes-any-road)
    (>= 1 the-monster-takes-any-road)
    (>= 1 big-bertha-takes-any-road)
    (>= 1 keep-truckin-takes-any-road)
    (>= 1 lonely-road-takes-any-road)
    (>= 1 dusty-trail-takes-any-road)
    (>= 1 little-guy-takes-any-road)
    (>= 1 putt-putt-takes-any-road)

    (= mega-rig-takes-any-road     (+ mega-rig-takes-sma-med mega-rig-takes-med-sma mega-rig-takes-sma-big mega-rig-takes-big-sma mega-rig-takes-med-big mega-rig-takes-big-med mega-rig-takes-now-sma mega-rig-takes-sma-now))
    (= the-monster-takes-any-road  (+ the-monster-takes-sma-med the-monster-takes-med-sma the-monster-takes-sma-big the-monster-takes-big-sma the-monster-takes-med-big the-monster-takes-big-med the-monster-takes-now-sma the-monster-takes-sma-now))
    (= big-bertha-takes-any-road   (+ big-bertha-takes-sma-med big-bertha-takes-med-sma big-bertha-takes-sma-big big-bertha-takes-big-sma big-bertha-takes-med-big big-bertha-takes-big-med big-bertha-takes-now-sma big-bertha-takes-sma-now))
    (= keep-truckin-takes-any-road (+ keep-truckin-takes-sma-med keep-truckin-takes-med-sma keep-truckin-takes-sma-big keep-truckin-takes-big-sma keep-truckin-takes-med-big keep-truckin-takes-big-med keep-truckin-takes-now-sma keep-truckin-takes-sma-now))
    (= lonely-road-takes-any-road  (+ lonely-road-takes-sma-med lonely-road-takes-med-sma lonely-road-takes-sma-big lonely-road-takes-big-sma lonely-road-takes-med-big lonely-road-takes-big-med lonely-road-takes-now-sma lonely-road-takes-sma-now))
    (= dusty-trail-takes-any-road  (+ dusty-trail-takes-sma-med dusty-trail-takes-med-sma dusty-trail-takes-sma-big dusty-trail-takes-big-sma dusty-trail-takes-med-big dusty-trail-takes-big-med dusty-trail-takes-now-sma dusty-trail-takes-sma-now))
    (= little-guy-takes-any-road   (+ little-guy-takes-sma-med little-guy-takes-med-sma little-guy-takes-sma-big little-guy-takes-big-sma little-guy-takes-med-big little-guy-takes-big-med little-guy-takes-now-sma little-guy-takes-sma-now))
    (= putt-putt-takes-any-road    (+ putt-putt-takes-sma-med putt-putt-takes-med-sma putt-putt-takes-sma-big putt-putt-takes-big-sma putt-putt-takes-med-big putt-putt-takes-big-med putt-putt-takes-now-sma putt-putt-takes-sma-now))

    (= mega-rig-sma-med-cost (* mega-rig-takes-sma-med (+ (.* truck-mega-rig-cost road-smallville-mediumville-len) road-smallville-mediumville-cost)))
    (= mega-rig-med-sma-cost (* mega-rig-takes-med-sma (+ (.* truck-mega-rig-cost road-mediumville-smallville-len) road-mediumville-smallville-cost)))
    (= mega-rig-sma-big-cost (* mega-rig-takes-sma-big (+ (.* truck-mega-rig-cost road-smallville-bigville-len) road-smallville-bigville-cost)))
    (= mega-rig-big-sma-cost (* mega-rig-takes-big-sma (+ (.* truck-mega-rig-cost road-bigville-smallville-len) road-bigville-smallville-cost)))
    (= mega-rig-med-big-cost (* mega-rig-takes-med-big (+ (.* truck-mega-rig-cost road-mediumville-bigville-len) road-mediumville-bigville-cost)))
    (= mega-rig-big-med-cost (* mega-rig-takes-big-med (+ (.* truck-mega-rig-cost road-bigville-mediumville-len) road-bigville-mediumville-cost)))
    (= mega-rig-now-sma-cost (* mega-rig-takes-now-sma (+ (.* truck-mega-rig-cost road-nowheresville-smallville-len) road-nowheresville-smallville-cost)))
    (= mega-rig-sma-now-cost (* mega-rig-takes-sma-now (+ (.* truck-mega-rig-cost road-smallville-nowheresville-len) road-smallville-nowheresville-cost)))
    (= the-monster-sma-med-cost (* the-monster-takes-sma-med (+ (.* truck-the-monster-cost road-smallville-mediumville-len) road-smallville-mediumville-cost)))
    (= the-monster-med-sma-cost (* the-monster-takes-med-sma (+ (.* truck-the-monster-cost road-mediumville-smallville-len) road-mediumville-smallville-cost)))
    (= the-monster-sma-big-cost (* the-monster-takes-sma-big (+ (.* truck-the-monster-cost road-smallville-bigville-len) road-smallville-bigville-cost)))
    (= the-monster-big-sma-cost (* the-monster-takes-big-sma (+ (.* truck-the-monster-cost road-bigville-smallville-len) road-bigville-smallville-cost)))
    (= the-monster-med-big-cost (* the-monster-takes-med-big (+ (.* truck-the-monster-cost road-mediumville-bigville-len) road-mediumville-bigville-cost)))
    (= the-monster-big-med-cost (* the-monster-takes-big-med (+ (.* truck-the-monster-cost road-bigville-mediumville-len) road-bigville-mediumville-cost)))
    (= the-monster-now-sma-cost (* the-monster-takes-now-sma (+ (.* truck-the-monster-cost road-nowheresville-smallville-len) road-nowheresville-smallville-cost)))
    (= the-monster-sma-now-cost (* the-monster-takes-sma-now (+ (.* truck-the-monster-cost road-smallville-nowheresville-len) road-smallville-nowheresville-cost)))
    (= big-bertha-sma-med-cost (* big-bertha-takes-sma-med (+ (.* truck-big-bertha-cost road-smallville-mediumville-len) road-smallville-mediumville-cost)))
    (= big-bertha-med-sma-cost (* big-bertha-takes-med-sma (+ (.* truck-big-bertha-cost road-mediumville-smallville-len) road-mediumville-smallville-cost)))
    (= big-bertha-sma-big-cost (* big-bertha-takes-sma-big (+ (.* truck-big-bertha-cost road-smallville-bigville-len) road-smallville-bigville-cost)))
    (= big-bertha-big-sma-cost (* big-bertha-takes-big-sma (+ (.* truck-big-bertha-cost road-bigville-smallville-len) road-bigville-smallville-cost)))
    (= big-bertha-med-big-cost (* big-bertha-takes-med-big (+ (.* truck-big-bertha-cost road-mediumville-bigville-len) road-mediumville-bigville-cost)))
    (= big-bertha-big-med-cost (* big-bertha-takes-big-med (+ (.* truck-big-bertha-cost road-bigville-mediumville-len) road-bigville-mediumville-cost)))
    (= big-bertha-now-sma-cost (* big-bertha-takes-now-sma (+ (.* truck-big-bertha-cost road-nowheresville-smallville-len) road-nowheresville-smallville-cost)))
    (= big-bertha-sma-now-cost (* big-bertha-takes-sma-now (+ (.* truck-big-bertha-cost road-smallville-nowheresville-len) road-smallville-nowheresville-cost)))
    (= keep-truckin-sma-med-cost (* keep-truckin-takes-sma-med (+ (.* truck-keep-truckin-cost road-smallville-mediumville-len) road-smallville-mediumville-cost)))
    (= keep-truckin-med-sma-cost (* keep-truckin-takes-med-sma (+ (.* truck-keep-truckin-cost road-mediumville-smallville-len) road-mediumville-smallville-cost)))
    (= keep-truckin-sma-big-cost (* keep-truckin-takes-sma-big (+ (.* truck-keep-truckin-cost road-smallville-bigville-len) road-smallville-bigville-cost)))
    (= keep-truckin-big-sma-cost (* keep-truckin-takes-big-sma (+ (.* truck-keep-truckin-cost road-bigville-smallville-len) road-bigville-smallville-cost)))
    (= keep-truckin-med-big-cost (* keep-truckin-takes-med-big (+ (.* truck-keep-truckin-cost road-mediumville-bigville-len) road-mediumville-bigville-cost)))
    (= keep-truckin-big-med-cost (* keep-truckin-takes-big-med (+ (.* truck-keep-truckin-cost road-bigville-mediumville-len) road-bigville-mediumville-cost)))
    (= keep-truckin-now-sma-cost (* keep-truckin-takes-now-sma (+ (.* truck-keep-truckin-cost road-nowheresville-smallville-len) road-nowheresville-smallville-cost)))
    (= keep-truckin-sma-now-cost (* keep-truckin-takes-sma-now (+ (.* truck-keep-truckin-cost road-smallville-nowheresville-len) road-smallville-nowheresville-cost)))
    (= lonely-road-sma-med-cost (* lonely-road-takes-sma-med (+ (.* truck-lonely-road-cost road-smallville-mediumville-len) road-smallville-mediumville-cost)))
    (= lonely-road-med-sma-cost (* lonely-road-takes-med-sma (+ (.* truck-lonely-road-cost road-mediumville-smallville-len) road-mediumville-smallville-cost)))
    (= lonely-road-sma-big-cost (* lonely-road-takes-sma-big (+ (.* truck-lonely-road-cost road-smallville-bigville-len) road-smallville-bigville-cost)))
    (= lonely-road-big-sma-cost (* lonely-road-takes-big-sma (+ (.* truck-lonely-road-cost road-bigville-smallville-len) road-bigville-smallville-cost)))
    (= lonely-road-med-big-cost (* lonely-road-takes-med-big (+ (.* truck-lonely-road-cost road-mediumville-bigville-len) road-mediumville-bigville-cost)))
    (= lonely-road-big-med-cost (* lonely-road-takes-big-med (+ (.* truck-lonely-road-cost road-bigville-mediumville-len) road-bigville-mediumville-cost)))
    (= lonely-road-now-sma-cost (* lonely-road-takes-now-sma (+ (.* truck-lonely-road-cost road-nowheresville-smallville-len) road-nowheresville-smallville-cost)))
    (= lonely-road-sma-now-cost (* lonely-road-takes-sma-now (+ (.* truck-lonely-road-cost road-smallville-nowheresville-len) road-smallville-nowheresville-cost)))
    (= dusty-trail-sma-med-cost (* dusty-trail-takes-sma-med (+ (.* truck-dusty-trail-cost road-smallville-mediumville-len) road-smallville-mediumville-cost)))
    (= dusty-trail-med-sma-cost (* dusty-trail-takes-med-sma (+ (.* truck-dusty-trail-cost road-mediumville-smallville-len) road-mediumville-smallville-cost)))
    (= dusty-trail-sma-big-cost (* dusty-trail-takes-sma-big (+ (.* truck-dusty-trail-cost road-smallville-bigville-len) road-smallville-bigville-cost)))
    (= dusty-trail-big-sma-cost (* dusty-trail-takes-big-sma (+ (.* truck-dusty-trail-cost road-bigville-smallville-len) road-bigville-smallville-cost)))
    (= dusty-trail-med-big-cost (* dusty-trail-takes-med-big (+ (.* truck-dusty-trail-cost road-mediumville-bigville-len) road-mediumville-bigville-cost)))
    (= dusty-trail-big-med-cost (* dusty-trail-takes-big-med (+ (.* truck-dusty-trail-cost road-bigville-mediumville-len) road-bigville-mediumville-cost)))
    (= dusty-trail-now-sma-cost (* dusty-trail-takes-now-sma (+ (.* truck-dusty-trail-cost road-nowheresville-smallville-len) road-nowheresville-smallville-cost)))
    (= dusty-trail-sma-now-cost (* dusty-trail-takes-sma-now (+ (.* truck-dusty-trail-cost road-smallville-nowheresville-len) road-smallville-nowheresville-cost)))
    (= little-guy-sma-med-cost (* little-guy-takes-sma-med (+ (.* truck-little-guy-cost road-smallville-mediumville-len) road-smallville-mediumville-cost)))
    (= little-guy-med-sma-cost (* little-guy-takes-med-sma (+ (.* truck-little-guy-cost road-mediumville-smallville-len) road-mediumville-smallville-cost)))
    (= little-guy-sma-big-cost (* little-guy-takes-sma-big (+ (.* truck-little-guy-cost road-smallville-bigville-len) road-smallville-bigville-cost)))
    (= little-guy-big-sma-cost (* little-guy-takes-big-sma (+ (.* truck-little-guy-cost road-bigville-smallville-len) road-bigville-smallville-cost)))
    (= little-guy-med-big-cost (* little-guy-takes-med-big (+ (.* truck-little-guy-cost road-mediumville-bigville-len) road-mediumville-bigville-cost)))
    (= little-guy-big-med-cost (* little-guy-takes-big-med (+ (.* truck-little-guy-cost road-bigville-mediumville-len) road-bigville-mediumville-cost)))
    (= little-guy-now-sma-cost (* little-guy-takes-now-sma (+ (.* truck-little-guy-cost road-nowheresville-smallville-len) road-nowheresville-smallville-cost)))
    (= little-guy-sma-now-cost (* little-guy-takes-sma-now (+ (.* truck-little-guy-cost road-smallville-nowheresville-len) road-smallville-nowheresville-cost)))
    (= putt-putt-sma-med-cost (* putt-putt-takes-sma-med (+ (.* truck-putt-putt-cost road-smallville-mediumville-len) road-smallville-mediumville-cost)))
    (= putt-putt-med-sma-cost (* putt-putt-takes-med-sma (+ (.* truck-putt-putt-cost road-mediumville-smallville-len) road-mediumville-smallville-cost)))
    (= putt-putt-sma-big-cost (* putt-putt-takes-sma-big (+ (.* truck-putt-putt-cost road-smallville-bigville-len) road-smallville-bigville-cost)))
    (= putt-putt-big-sma-cost (* putt-putt-takes-big-sma (+ (.* truck-putt-putt-cost road-bigville-smallville-len) road-bigville-smallville-cost)))
    (= putt-putt-med-big-cost (* putt-putt-takes-med-big (+ (.* truck-putt-putt-cost road-mediumville-bigville-len) road-mediumville-bigville-cost)))
    (= putt-putt-big-med-cost (* putt-putt-takes-big-med (+ (.* truck-putt-putt-cost road-bigville-mediumville-len) road-bigville-mediumville-cost)))
    (= putt-putt-now-sma-cost (* putt-putt-takes-now-sma (+ (.* truck-putt-putt-cost road-nowheresville-smallville-len) road-nowheresville-smallville-cost)))
    (= putt-putt-sma-now-cost (* putt-putt-takes-sma-now (+ (.* truck-putt-putt-cost road-smallville-nowheresville-len) road-smallville-nowheresville-cost)))

    (= mega-rig-cost     (+ mega-rig-sma-med-cost mega-rig-med-sma-cost mega-rig-sma-big-cost mega-rig-big-sma-cost mega-rig-med-big-cost mega-rig-big-med-cost mega-rig-now-sma-cost mega-rig-sma-now-cost))
    (= the-monster-cost  (+ the-monster-sma-med-cost the-monster-med-sma-cost the-monster-sma-big-cost the-monster-big-sma-cost the-monster-med-big-cost the-monster-big-med-cost the-monster-now-sma-cost the-monster-sma-now-cost))
    (= big-bertha-cost   (+ big-bertha-sma-med-cost big-bertha-med-sma-cost big-bertha-sma-big-cost big-bertha-big-sma-cost big-bertha-med-big-cost big-bertha-big-med-cost big-bertha-now-sma-cost big-bertha-sma-now-cost))
    (= keep-truckin-cost (+ keep-truckin-sma-med-cost keep-truckin-med-sma-cost keep-truckin-sma-big-cost keep-truckin-big-sma-cost keep-truckin-med-big-cost keep-truckin-big-med-cost keep-truckin-now-sma-cost keep-truckin-sma-now-cost))
    (= lonely-road-cost  (+ lonely-road-sma-med-cost lonely-road-med-sma-cost lonely-road-sma-big-cost lonely-road-big-sma-cost lonely-road-med-big-cost lonely-road-big-med-cost lonely-road-now-sma-cost lonely-road-sma-now-cost))
    (= dusty-trail-cost  (+ dusty-trail-sma-med-cost dusty-trail-med-sma-cost dusty-trail-sma-big-cost dusty-trail-big-sma-cost dusty-trail-med-big-cost dusty-trail-big-med-cost dusty-trail-now-sma-cost dusty-trail-sma-now-cost))
    (= little-guy-cost   (+ little-guy-sma-med-cost little-guy-med-sma-cost little-guy-sma-big-cost little-guy-big-sma-cost little-guy-med-big-cost little-guy-big-med-cost little-guy-now-sma-cost little-guy-sma-now-cost))
    (= putt-putt-cost    (+ putt-putt-sma-med-cost putt-putt-med-sma-cost putt-putt-sma-big-cost putt-putt-big-sma-cost putt-putt-med-big-cost putt-putt-big-med-cost putt-putt-now-sma-cost putt-putt-sma-now-cost))

    (= sma-apples-stock (* sma-has-warehouse sma-apples-would-stock))
    (= sma-banana-stock (* sma-has-warehouse sma-banana-would-stock))
    (= sma-orange-stock (* sma-has-warehouse sma-orange-would-stock))
    (= sma-grapes-stock (* sma-has-warehouse sma-grapes-would-stock))
    (= med-apples-stock (* med-has-warehouse med-apples-would-stock))
    (= med-banana-stock (* med-has-warehouse med-banana-would-stock))
    (= med-orange-stock (* med-has-warehouse med-orange-would-stock))
    (= med-grapes-stock (* med-has-warehouse med-grapes-would-stock))
    (= big-apples-stock (* big-has-warehouse big-apples-would-stock))
    (= big-banana-stock (* big-has-warehouse big-banana-would-stock))
    (= big-orange-stock (* big-has-warehouse big-orange-would-stock))
    (= big-grapes-stock (* big-has-warehouse big-grapes-would-stock))
    (= now-apples-stock (* now-has-warehouse now-apples-would-stock))
    (= now-banana-stock (* now-has-warehouse now-banana-would-stock))
    (= now-orange-stock (* now-has-warehouse now-orange-would-stock))
    (= now-grapes-stock (* now-has-warehouse now-grapes-would-stock))

    (<= sma-stock city-smallville-capacity)
    (= sma-stock
       (+ (.* product-apples-size sma-apples-stock)
          (.* product-banana-size sma-banana-stock)
          (.* product-orange-size sma-orange-stock)
          (.* product-grapes-size sma-grapes-stock)))
    (<= med-stock city-mediumville-capacity)
    (= med-stock
       (+ (.* product-apples-size med-apples-stock)
          (.* product-banana-size med-banana-stock)
          (.* product-orange-size med-orange-stock)
          (.* product-grapes-size med-grapes-stock)))
    (<= big-stock city-bigville-capacity)
    (= big-stock
       (+ (.* product-apples-size big-apples-stock)
          (.* product-banana-size big-banana-stock)
          (.* product-orange-size big-orange-stock)
          (.* product-grapes-size big-grapes-stock)))
    (<= now-stock city-nowheresville-capacity)
    (= now-stock
       (+ (.* product-apples-size now-apples-stock)
          (.* product-banana-size now-banana-stock)
          (.* product-orange-size now-orange-stock)
          (.* product-grapes-size now-grapes-stock)))

    (= mega-rig-apples-stock (* mega-rig-takes-any-road mega-rig-apples-would-stock))
    (= mega-rig-banana-stock (* mega-rig-takes-any-road mega-rig-banana-would-stock))
    (= mega-rig-orange-stock (* mega-rig-takes-any-road mega-rig-orange-would-stock))
    (= mega-rig-grapes-stock (* mega-rig-takes-any-road mega-rig-grapes-would-stock))
    (= the-monster-apples-stock (* the-monster-takes-any-road the-monster-apples-would-stock))
    (= the-monster-banana-stock (* the-monster-takes-any-road the-monster-banana-would-stock))
    (= the-monster-orange-stock (* the-monster-takes-any-road the-monster-orange-would-stock))
    (= the-monster-grapes-stock (* the-monster-takes-any-road the-monster-grapes-would-stock))
    (= big-bertha-apples-stock (* big-bertha-takes-any-road big-bertha-apples-would-stock))
    (= big-bertha-banana-stock (* big-bertha-takes-any-road big-bertha-banana-would-stock))
    (= big-bertha-orange-stock (* big-bertha-takes-any-road big-bertha-orange-would-stock))
    (= big-bertha-grapes-stock (* big-bertha-takes-any-road big-bertha-grapes-would-stock))
    (= keep-truckin-apples-stock (* keep-truckin-takes-any-road keep-truckin-apples-would-stock))
    (= keep-truckin-banana-stock (* keep-truckin-takes-any-road keep-truckin-banana-would-stock))
    (= keep-truckin-orange-stock (* keep-truckin-takes-any-road keep-truckin-orange-would-stock))
    (= keep-truckin-grapes-stock (* keep-truckin-takes-any-road keep-truckin-grapes-would-stock))
    (= lonely-road-apples-stock (* lonely-road-takes-any-road lonely-road-apples-would-stock))
    (= lonely-road-banana-stock (* lonely-road-takes-any-road lonely-road-banana-would-stock))
    (= lonely-road-orange-stock (* lonely-road-takes-any-road lonely-road-orange-would-stock))
    (= lonely-road-grapes-stock (* lonely-road-takes-any-road lonely-road-grapes-would-stock))
    (= dusty-trail-apples-stock (* dusty-trail-takes-any-road dusty-trail-apples-would-stock))
    (= dusty-trail-banana-stock (* dusty-trail-takes-any-road dusty-trail-banana-would-stock))
    (= dusty-trail-orange-stock (* dusty-trail-takes-any-road dusty-trail-orange-would-stock))
    (= dusty-trail-grapes-stock (* dusty-trail-takes-any-road dusty-trail-grapes-would-stock))
    (= little-guy-apples-stock (* little-guy-takes-any-road little-guy-apples-would-stock))
    (= little-guy-banana-stock (* little-guy-takes-any-road little-guy-banana-would-stock))
    (= little-guy-orange-stock (* little-guy-takes-any-road little-guy-orange-would-stock))
    (= little-guy-grapes-stock (* little-guy-takes-any-road little-guy-grapes-would-stock))
    (= putt-putt-apples-stock (* putt-putt-takes-any-road putt-putt-apples-would-stock))
    (= putt-putt-banana-stock (* putt-putt-takes-any-road putt-putt-banana-would-stock))
    (= putt-putt-orange-stock (* putt-putt-takes-any-road putt-putt-orange-would-stock))
    (= putt-putt-grapes-stock (* putt-putt-takes-any-road putt-putt-grapes-would-stock))

    (<= mega-rig-loading truck-mega-rig-cap)
    (= mega-rig-loading
       (+ (.* product-apples-size mega-rig-apples-stock)
          (.* product-banana-size mega-rig-banana-stock)
          (.* product-orange-size mega-rig-orange-stock)
          (.* product-grapes-size mega-rig-grapes-stock)))
    (<= the-monster-loading truck-the-monster-cap)
    (= the-monster-loading
       (+ (.* product-apples-size the-monster-apples-stock)
          (.* product-banana-size the-monster-banana-stock)
          (.* product-orange-size the-monster-orange-stock)
          (.* product-grapes-size the-monster-grapes-stock)))
    (<= big-bertha-loading truck-big-bertha-cap)
    (= big-bertha-loading
       (+ (.* product-apples-size big-bertha-apples-stock)
          (.* product-banana-size big-bertha-banana-stock)
          (.* product-orange-size big-bertha-orange-stock)
          (.* product-grapes-size big-bertha-grapes-stock)))
    (<= keep-truckin-loading truck-keep-truckin-cap)
    (= keep-truckin-loading
       (+ (.* product-apples-size keep-truckin-apples-stock)
          (.* product-banana-size keep-truckin-banana-stock)
          (.* product-orange-size keep-truckin-orange-stock)
          (.* product-grapes-size keep-truckin-grapes-stock)))
    (<= lonely-road-loading truck-lonely-road-cap)
    (= lonely-road-loading
       (+ (.* product-apples-size lonely-road-apples-stock)
          (.* product-banana-size lonely-road-banana-stock)
          (.* product-orange-size lonely-road-orange-stock)
          (.* product-grapes-size lonely-road-grapes-stock)))
    (<= dusty-trail-loading truck-dusty-trail-cap)
    (= dusty-trail-loading
       (+ (.* product-apples-size dusty-trail-apples-stock)
          (.* product-banana-size dusty-trail-banana-stock)
          (.* product-orange-size dusty-trail-orange-stock)
          (.* product-grapes-size dusty-trail-grapes-stock)))
    (<= little-guy-loading truck-little-guy-cap)
    (= little-guy-loading
       (+ (.* product-apples-size little-guy-apples-stock)
          (.* product-banana-size little-guy-banana-stock)
          (.* product-orange-size little-guy-orange-stock)
          (.* product-grapes-size little-guy-grapes-stock)))
    (<= putt-putt-loading truck-putt-putt-cap)
    (= putt-putt-loading
       (+ (.* product-apples-size putt-putt-apples-stock)
          (.* product-banana-size putt-putt-banana-stock)
          (.* product-orange-size putt-putt-orange-stock)
          (.* product-grapes-size putt-putt-grapes-stock)))

    (= sma-apples-imports
      (+ (- (* mega-rig-takes-med-sma mega-rig-apples-stock) (* mega-rig-takes-sma-med mega-rig-apples-stock))
         (- (* mega-rig-takes-big-sma mega-rig-apples-stock) (* mega-rig-takes-sma-big mega-rig-apples-stock))
         (- (* mega-rig-takes-now-sma mega-rig-apples-stock) (* mega-rig-takes-sma-now mega-rig-apples-stock))
         (- (* the-monster-takes-med-sma the-monster-apples-stock) (* the-monster-takes-sma-med the-monster-apples-stock))
         (- (* the-monster-takes-big-sma the-monster-apples-stock) (* the-monster-takes-sma-big the-monster-apples-stock))
         (- (* the-monster-takes-now-sma the-monster-apples-stock) (* the-monster-takes-sma-now the-monster-apples-stock))
         (- (* big-bertha-takes-med-sma big-bertha-apples-stock) (* big-bertha-takes-sma-med big-bertha-apples-stock))
         (- (* big-bertha-takes-big-sma big-bertha-apples-stock) (* big-bertha-takes-sma-big big-bertha-apples-stock))
         (- (* big-bertha-takes-now-sma big-bertha-apples-stock) (* big-bertha-takes-sma-now big-bertha-apples-stock))
         (- (* keep-truckin-takes-med-sma keep-truckin-apples-stock) (* keep-truckin-takes-sma-med keep-truckin-apples-stock))
         (- (* keep-truckin-takes-big-sma keep-truckin-apples-stock) (* keep-truckin-takes-sma-big keep-truckin-apples-stock))
         (- (* keep-truckin-takes-now-sma keep-truckin-apples-stock) (* keep-truckin-takes-sma-now keep-truckin-apples-stock))
         (- (* lonely-road-takes-med-sma lonely-road-apples-stock) (* lonely-road-takes-sma-med lonely-road-apples-stock))
         (- (* lonely-road-takes-big-sma lonely-road-apples-stock) (* lonely-road-takes-sma-big lonely-road-apples-stock))
         (- (* lonely-road-takes-now-sma lonely-road-apples-stock) (* lonely-road-takes-sma-now lonely-road-apples-stock))
         (- (* dusty-trail-takes-med-sma dusty-trail-apples-stock) (* dusty-trail-takes-sma-med dusty-trail-apples-stock))
         (- (* dusty-trail-takes-big-sma dusty-trail-apples-stock) (* dusty-trail-takes-sma-big dusty-trail-apples-stock))
         (- (* dusty-trail-takes-now-sma dusty-trail-apples-stock) (* dusty-trail-takes-sma-now dusty-trail-apples-stock))
         (- (* little-guy-takes-med-sma little-guy-apples-stock) (* little-guy-takes-sma-med little-guy-apples-stock))
         (- (* little-guy-takes-big-sma little-guy-apples-stock) (* little-guy-takes-sma-big little-guy-apples-stock))
         (- (* little-guy-takes-now-sma little-guy-apples-stock) (* little-guy-takes-sma-now little-guy-apples-stock))
         (- (* putt-putt-takes-med-sma putt-putt-apples-stock) (* putt-putt-takes-sma-med putt-putt-apples-stock))
         (- (* putt-putt-takes-big-sma putt-putt-apples-stock) (* putt-putt-takes-sma-big putt-putt-apples-stock))
         (- (* putt-putt-takes-now-sma putt-putt-apples-stock) (* putt-putt-takes-sma-now putt-putt-apples-stock))))
    (= sma-banana-imports
      (+ (- (* mega-rig-takes-med-sma mega-rig-banana-stock) (* mega-rig-takes-sma-med mega-rig-banana-stock))
         (- (* mega-rig-takes-big-sma mega-rig-banana-stock) (* mega-rig-takes-sma-big mega-rig-banana-stock))
         (- (* mega-rig-takes-now-sma mega-rig-banana-stock) (* mega-rig-takes-sma-now mega-rig-banana-stock))
         (- (* the-monster-takes-med-sma the-monster-banana-stock) (* the-monster-takes-sma-med the-monster-banana-stock))
         (- (* the-monster-takes-big-sma the-monster-banana-stock) (* the-monster-takes-sma-big the-monster-banana-stock))
         (- (* the-monster-takes-now-sma the-monster-banana-stock) (* the-monster-takes-sma-now the-monster-banana-stock))
         (- (* big-bertha-takes-med-sma big-bertha-banana-stock) (* big-bertha-takes-sma-med big-bertha-banana-stock))
         (- (* big-bertha-takes-big-sma big-bertha-banana-stock) (* big-bertha-takes-sma-big big-bertha-banana-stock))
         (- (* big-bertha-takes-now-sma big-bertha-banana-stock) (* big-bertha-takes-sma-now big-bertha-banana-stock))
         (- (* keep-truckin-takes-med-sma keep-truckin-banana-stock) (* keep-truckin-takes-sma-med keep-truckin-banana-stock))
         (- (* keep-truckin-takes-big-sma keep-truckin-banana-stock) (* keep-truckin-takes-sma-big keep-truckin-banana-stock))
         (- (* keep-truckin-takes-now-sma keep-truckin-banana-stock) (* keep-truckin-takes-sma-now keep-truckin-banana-stock))
         (- (* lonely-road-takes-med-sma lonely-road-banana-stock) (* lonely-road-takes-sma-med lonely-road-banana-stock))
         (- (* lonely-road-takes-big-sma lonely-road-banana-stock) (* lonely-road-takes-sma-big lonely-road-banana-stock))
         (- (* lonely-road-takes-now-sma lonely-road-banana-stock) (* lonely-road-takes-sma-now lonely-road-banana-stock))
         (- (* dusty-trail-takes-med-sma dusty-trail-banana-stock) (* dusty-trail-takes-sma-med dusty-trail-banana-stock))
         (- (* dusty-trail-takes-big-sma dusty-trail-banana-stock) (* dusty-trail-takes-sma-big dusty-trail-banana-stock))
         (- (* dusty-trail-takes-now-sma dusty-trail-banana-stock) (* dusty-trail-takes-sma-now dusty-trail-banana-stock))
         (- (* little-guy-takes-med-sma little-guy-banana-stock) (* little-guy-takes-sma-med little-guy-banana-stock))
         (- (* little-guy-takes-big-sma little-guy-banana-stock) (* little-guy-takes-sma-big little-guy-banana-stock))
         (- (* little-guy-takes-now-sma little-guy-banana-stock) (* little-guy-takes-sma-now little-guy-banana-stock))
         (- (* putt-putt-takes-med-sma putt-putt-banana-stock) (* putt-putt-takes-sma-med putt-putt-banana-stock))
         (- (* putt-putt-takes-big-sma putt-putt-banana-stock) (* putt-putt-takes-sma-big putt-putt-banana-stock))
         (- (* putt-putt-takes-now-sma putt-putt-banana-stock) (* putt-putt-takes-sma-now putt-putt-banana-stock))))
    (= sma-orange-imports
      (+ (- (* mega-rig-takes-med-sma mega-rig-orange-stock) (* mega-rig-takes-sma-med mega-rig-orange-stock))
         (- (* mega-rig-takes-big-sma mega-rig-orange-stock) (* mega-rig-takes-sma-big mega-rig-orange-stock))
         (- (* mega-rig-takes-now-sma mega-rig-orange-stock) (* mega-rig-takes-sma-now mega-rig-orange-stock))
         (- (* the-monster-takes-med-sma the-monster-orange-stock) (* the-monster-takes-sma-med the-monster-orange-stock))
         (- (* the-monster-takes-big-sma the-monster-orange-stock) (* the-monster-takes-sma-big the-monster-orange-stock))
         (- (* the-monster-takes-now-sma the-monster-orange-stock) (* the-monster-takes-sma-now the-monster-orange-stock))
         (- (* big-bertha-takes-med-sma big-bertha-orange-stock) (* big-bertha-takes-sma-med big-bertha-orange-stock))
         (- (* big-bertha-takes-big-sma big-bertha-orange-stock) (* big-bertha-takes-sma-big big-bertha-orange-stock))
         (- (* big-bertha-takes-now-sma big-bertha-orange-stock) (* big-bertha-takes-sma-now big-bertha-orange-stock))
         (- (* keep-truckin-takes-med-sma keep-truckin-orange-stock) (* keep-truckin-takes-sma-med keep-truckin-orange-stock))
         (- (* keep-truckin-takes-big-sma keep-truckin-orange-stock) (* keep-truckin-takes-sma-big keep-truckin-orange-stock))
         (- (* keep-truckin-takes-now-sma keep-truckin-orange-stock) (* keep-truckin-takes-sma-now keep-truckin-orange-stock))
         (- (* lonely-road-takes-med-sma lonely-road-orange-stock) (* lonely-road-takes-sma-med lonely-road-orange-stock))
         (- (* lonely-road-takes-big-sma lonely-road-orange-stock) (* lonely-road-takes-sma-big lonely-road-orange-stock))
         (- (* lonely-road-takes-now-sma lonely-road-orange-stock) (* lonely-road-takes-sma-now lonely-road-orange-stock))
         (- (* dusty-trail-takes-med-sma dusty-trail-orange-stock) (* dusty-trail-takes-sma-med dusty-trail-orange-stock))
         (- (* dusty-trail-takes-big-sma dusty-trail-orange-stock) (* dusty-trail-takes-sma-big dusty-trail-orange-stock))
         (- (* dusty-trail-takes-now-sma dusty-trail-orange-stock) (* dusty-trail-takes-sma-now dusty-trail-orange-stock))
         (- (* little-guy-takes-med-sma little-guy-orange-stock) (* little-guy-takes-sma-med little-guy-orange-stock))
         (- (* little-guy-takes-big-sma little-guy-orange-stock) (* little-guy-takes-sma-big little-guy-orange-stock))
         (- (* little-guy-takes-now-sma little-guy-orange-stock) (* little-guy-takes-sma-now little-guy-orange-stock))
         (- (* putt-putt-takes-med-sma putt-putt-orange-stock) (* putt-putt-takes-sma-med putt-putt-orange-stock))
         (- (* putt-putt-takes-big-sma putt-putt-orange-stock) (* putt-putt-takes-sma-big putt-putt-orange-stock))
         (- (* putt-putt-takes-now-sma putt-putt-orange-stock) (* putt-putt-takes-sma-now putt-putt-orange-stock))))
    (= sma-grapes-imports
      (+ (- (* mega-rig-takes-med-sma mega-rig-grapes-stock) (* mega-rig-takes-sma-med mega-rig-grapes-stock))
         (- (* mega-rig-takes-big-sma mega-rig-grapes-stock) (* mega-rig-takes-sma-big mega-rig-grapes-stock))
         (- (* mega-rig-takes-now-sma mega-rig-grapes-stock) (* mega-rig-takes-sma-now mega-rig-grapes-stock))
         (- (* the-monster-takes-med-sma the-monster-grapes-stock) (* the-monster-takes-sma-med the-monster-grapes-stock))
         (- (* the-monster-takes-big-sma the-monster-grapes-stock) (* the-monster-takes-sma-big the-monster-grapes-stock))
         (- (* the-monster-takes-now-sma the-monster-grapes-stock) (* the-monster-takes-sma-now the-monster-grapes-stock))
         (- (* big-bertha-takes-med-sma big-bertha-grapes-stock) (* big-bertha-takes-sma-med big-bertha-grapes-stock))
         (- (* big-bertha-takes-big-sma big-bertha-grapes-stock) (* big-bertha-takes-sma-big big-bertha-grapes-stock))
         (- (* big-bertha-takes-now-sma big-bertha-grapes-stock) (* big-bertha-takes-sma-now big-bertha-grapes-stock))
         (- (* keep-truckin-takes-med-sma keep-truckin-grapes-stock) (* keep-truckin-takes-sma-med keep-truckin-grapes-stock))
         (- (* keep-truckin-takes-big-sma keep-truckin-grapes-stock) (* keep-truckin-takes-sma-big keep-truckin-grapes-stock))
         (- (* keep-truckin-takes-now-sma keep-truckin-grapes-stock) (* keep-truckin-takes-sma-now keep-truckin-grapes-stock))
         (- (* lonely-road-takes-med-sma lonely-road-grapes-stock) (* lonely-road-takes-sma-med lonely-road-grapes-stock))
         (- (* lonely-road-takes-big-sma lonely-road-grapes-stock) (* lonely-road-takes-sma-big lonely-road-grapes-stock))
         (- (* lonely-road-takes-now-sma lonely-road-grapes-stock) (* lonely-road-takes-sma-now lonely-road-grapes-stock))
         (- (* dusty-trail-takes-med-sma dusty-trail-grapes-stock) (* dusty-trail-takes-sma-med dusty-trail-grapes-stock))
         (- (* dusty-trail-takes-big-sma dusty-trail-grapes-stock) (* dusty-trail-takes-sma-big dusty-trail-grapes-stock))
         (- (* dusty-trail-takes-now-sma dusty-trail-grapes-stock) (* dusty-trail-takes-sma-now dusty-trail-grapes-stock))
         (- (* little-guy-takes-med-sma little-guy-grapes-stock) (* little-guy-takes-sma-med little-guy-grapes-stock))
         (- (* little-guy-takes-big-sma little-guy-grapes-stock) (* little-guy-takes-sma-big little-guy-grapes-stock))
         (- (* little-guy-takes-now-sma little-guy-grapes-stock) (* little-guy-takes-sma-now little-guy-grapes-stock))
         (- (* putt-putt-takes-med-sma putt-putt-grapes-stock) (* putt-putt-takes-sma-med putt-putt-grapes-stock))
         (- (* putt-putt-takes-big-sma putt-putt-grapes-stock) (* putt-putt-takes-sma-big putt-putt-grapes-stock))
         (- (* putt-putt-takes-now-sma putt-putt-grapes-stock) (* putt-putt-takes-sma-now putt-putt-grapes-stock))))
    (= med-apples-imports
      (+ (- (* mega-rig-takes-sma-med mega-rig-apples-stock) (* mega-rig-takes-med-sma mega-rig-apples-stock))
         (- (* mega-rig-takes-big-med mega-rig-apples-stock) (* mega-rig-takes-med-big mega-rig-apples-stock))
         (- (* the-monster-takes-sma-med the-monster-apples-stock) (* the-monster-takes-med-sma the-monster-apples-stock))
         (- (* the-monster-takes-big-med the-monster-apples-stock) (* the-monster-takes-med-big the-monster-apples-stock))
         (- (* big-bertha-takes-sma-med big-bertha-apples-stock) (* big-bertha-takes-med-sma big-bertha-apples-stock))
         (- (* big-bertha-takes-big-med big-bertha-apples-stock) (* big-bertha-takes-med-big big-bertha-apples-stock))
         (- (* keep-truckin-takes-sma-med keep-truckin-apples-stock) (* keep-truckin-takes-med-sma keep-truckin-apples-stock))
         (- (* keep-truckin-takes-big-med keep-truckin-apples-stock) (* keep-truckin-takes-med-big keep-truckin-apples-stock))
         (- (* lonely-road-takes-sma-med lonely-road-apples-stock) (* lonely-road-takes-med-sma lonely-road-apples-stock))
         (- (* lonely-road-takes-big-med lonely-road-apples-stock) (* lonely-road-takes-med-big lonely-road-apples-stock))
         (- (* dusty-trail-takes-sma-med dusty-trail-apples-stock) (* dusty-trail-takes-med-sma dusty-trail-apples-stock))
         (- (* dusty-trail-takes-big-med dusty-trail-apples-stock) (* dusty-trail-takes-med-big dusty-trail-apples-stock))
         (- (* little-guy-takes-sma-med little-guy-apples-stock) (* little-guy-takes-med-sma little-guy-apples-stock))
         (- (* little-guy-takes-big-med little-guy-apples-stock) (* little-guy-takes-med-big little-guy-apples-stock))
         (- (* putt-putt-takes-sma-med putt-putt-apples-stock) (* putt-putt-takes-med-sma putt-putt-apples-stock))
         (- (* putt-putt-takes-big-med putt-putt-apples-stock) (* putt-putt-takes-med-big putt-putt-apples-stock))))
    (= med-banana-imports
      (+ (- (* mega-rig-takes-sma-med mega-rig-banana-stock) (* mega-rig-takes-med-sma mega-rig-banana-stock))
         (- (* mega-rig-takes-big-med mega-rig-banana-stock) (* mega-rig-takes-med-big mega-rig-banana-stock))
         (- (* the-monster-takes-sma-med the-monster-banana-stock) (* the-monster-takes-med-sma the-monster-banana-stock))
         (- (* the-monster-takes-big-med the-monster-banana-stock) (* the-monster-takes-med-big the-monster-banana-stock))
         (- (* big-bertha-takes-sma-med big-bertha-banana-stock) (* big-bertha-takes-med-sma big-bertha-banana-stock))
         (- (* big-bertha-takes-big-med big-bertha-banana-stock) (* big-bertha-takes-med-big big-bertha-banana-stock))
         (- (* keep-truckin-takes-sma-med keep-truckin-banana-stock) (* keep-truckin-takes-med-sma keep-truckin-banana-stock))
         (- (* keep-truckin-takes-big-med keep-truckin-banana-stock) (* keep-truckin-takes-med-big keep-truckin-banana-stock))
         (- (* lonely-road-takes-sma-med lonely-road-banana-stock) (* lonely-road-takes-med-sma lonely-road-banana-stock))
         (- (* lonely-road-takes-big-med lonely-road-banana-stock) (* lonely-road-takes-med-big lonely-road-banana-stock))
         (- (* dusty-trail-takes-sma-med dusty-trail-banana-stock) (* dusty-trail-takes-med-sma dusty-trail-banana-stock))
         (- (* dusty-trail-takes-big-med dusty-trail-banana-stock) (* dusty-trail-takes-med-big dusty-trail-banana-stock))
         (- (* little-guy-takes-sma-med little-guy-banana-stock) (* little-guy-takes-med-sma little-guy-banana-stock))
         (- (* little-guy-takes-big-med little-guy-banana-stock) (* little-guy-takes-med-big little-guy-banana-stock))
         (- (* putt-putt-takes-sma-med putt-putt-banana-stock) (* putt-putt-takes-med-sma putt-putt-banana-stock))
         (- (* putt-putt-takes-big-med putt-putt-banana-stock) (* putt-putt-takes-med-big putt-putt-banana-stock))))
    (= med-orange-imports
      (+ (- (* mega-rig-takes-sma-med mega-rig-orange-stock) (* mega-rig-takes-med-sma mega-rig-orange-stock))
         (- (* mega-rig-takes-big-med mega-rig-orange-stock) (* mega-rig-takes-med-big mega-rig-orange-stock))
         (- (* the-monster-takes-sma-med the-monster-orange-stock) (* the-monster-takes-med-sma the-monster-orange-stock))
         (- (* the-monster-takes-big-med the-monster-orange-stock) (* the-monster-takes-med-big the-monster-orange-stock))
         (- (* big-bertha-takes-sma-med big-bertha-orange-stock) (* big-bertha-takes-med-sma big-bertha-orange-stock))
         (- (* big-bertha-takes-big-med big-bertha-orange-stock) (* big-bertha-takes-med-big big-bertha-orange-stock))
         (- (* keep-truckin-takes-sma-med keep-truckin-orange-stock) (* keep-truckin-takes-med-sma keep-truckin-orange-stock))
         (- (* keep-truckin-takes-big-med keep-truckin-orange-stock) (* keep-truckin-takes-med-big keep-truckin-orange-stock))
         (- (* lonely-road-takes-sma-med lonely-road-orange-stock) (* lonely-road-takes-med-sma lonely-road-orange-stock))
         (- (* lonely-road-takes-big-med lonely-road-orange-stock) (* lonely-road-takes-med-big lonely-road-orange-stock))
         (- (* dusty-trail-takes-sma-med dusty-trail-orange-stock) (* dusty-trail-takes-med-sma dusty-trail-orange-stock))
         (- (* dusty-trail-takes-big-med dusty-trail-orange-stock) (* dusty-trail-takes-med-big dusty-trail-orange-stock))
         (- (* little-guy-takes-sma-med little-guy-orange-stock) (* little-guy-takes-med-sma little-guy-orange-stock))
         (- (* little-guy-takes-big-med little-guy-orange-stock) (* little-guy-takes-med-big little-guy-orange-stock))
         (- (* putt-putt-takes-sma-med putt-putt-orange-stock) (* putt-putt-takes-med-sma putt-putt-orange-stock))
         (- (* putt-putt-takes-big-med putt-putt-orange-stock) (* putt-putt-takes-med-big putt-putt-orange-stock))))
    (= med-grapes-imports
      (+ (- (* mega-rig-takes-sma-med mega-rig-grapes-stock) (* mega-rig-takes-med-sma mega-rig-grapes-stock))
         (- (* mega-rig-takes-big-med mega-rig-grapes-stock) (* mega-rig-takes-med-big mega-rig-grapes-stock))
         (- (* the-monster-takes-sma-med the-monster-grapes-stock) (* the-monster-takes-med-sma the-monster-grapes-stock))
         (- (* the-monster-takes-big-med the-monster-grapes-stock) (* the-monster-takes-med-big the-monster-grapes-stock))
         (- (* big-bertha-takes-sma-med big-bertha-grapes-stock) (* big-bertha-takes-med-sma big-bertha-grapes-stock))
         (- (* big-bertha-takes-big-med big-bertha-grapes-stock) (* big-bertha-takes-med-big big-bertha-grapes-stock))
         (- (* keep-truckin-takes-sma-med keep-truckin-grapes-stock) (* keep-truckin-takes-med-sma keep-truckin-grapes-stock))
         (- (* keep-truckin-takes-big-med keep-truckin-grapes-stock) (* keep-truckin-takes-med-big keep-truckin-grapes-stock))
         (- (* lonely-road-takes-sma-med lonely-road-grapes-stock) (* lonely-road-takes-med-sma lonely-road-grapes-stock))
         (- (* lonely-road-takes-big-med lonely-road-grapes-stock) (* lonely-road-takes-med-big lonely-road-grapes-stock))
         (- (* dusty-trail-takes-sma-med dusty-trail-grapes-stock) (* dusty-trail-takes-med-sma dusty-trail-grapes-stock))
         (- (* dusty-trail-takes-big-med dusty-trail-grapes-stock) (* dusty-trail-takes-med-big dusty-trail-grapes-stock))
         (- (* little-guy-takes-sma-med little-guy-grapes-stock) (* little-guy-takes-med-sma little-guy-grapes-stock))
         (- (* little-guy-takes-big-med little-guy-grapes-stock) (* little-guy-takes-med-big little-guy-grapes-stock))
         (- (* putt-putt-takes-sma-med putt-putt-grapes-stock) (* putt-putt-takes-med-sma putt-putt-grapes-stock))
         (- (* putt-putt-takes-big-med putt-putt-grapes-stock) (* putt-putt-takes-med-big putt-putt-grapes-stock))))
    (= big-apples-imports
      (+ (- (* mega-rig-takes-sma-big mega-rig-apples-stock) (* mega-rig-takes-big-sma mega-rig-apples-stock))
         (- (* mega-rig-takes-med-big mega-rig-apples-stock) (* mega-rig-takes-big-med mega-rig-apples-stock))
         (- (* the-monster-takes-sma-big the-monster-apples-stock) (* the-monster-takes-big-sma the-monster-apples-stock))
         (- (* the-monster-takes-med-big the-monster-apples-stock) (* the-monster-takes-big-med the-monster-apples-stock))
         (- (* big-bertha-takes-sma-big big-bertha-apples-stock) (* big-bertha-takes-big-sma big-bertha-apples-stock))
         (- (* big-bertha-takes-med-big big-bertha-apples-stock) (* big-bertha-takes-big-med big-bertha-apples-stock))
         (- (* keep-truckin-takes-sma-big keep-truckin-apples-stock) (* keep-truckin-takes-big-sma keep-truckin-apples-stock))
         (- (* keep-truckin-takes-med-big keep-truckin-apples-stock) (* keep-truckin-takes-big-med keep-truckin-apples-stock))
         (- (* lonely-road-takes-sma-big lonely-road-apples-stock) (* lonely-road-takes-big-sma lonely-road-apples-stock))
         (- (* lonely-road-takes-med-big lonely-road-apples-stock) (* lonely-road-takes-big-med lonely-road-apples-stock))
         (- (* dusty-trail-takes-sma-big dusty-trail-apples-stock) (* dusty-trail-takes-big-sma dusty-trail-apples-stock))
         (- (* dusty-trail-takes-med-big dusty-trail-apples-stock) (* dusty-trail-takes-big-med dusty-trail-apples-stock))
         (- (* little-guy-takes-sma-big little-guy-apples-stock) (* little-guy-takes-big-sma little-guy-apples-stock))
         (- (* little-guy-takes-med-big little-guy-apples-stock) (* little-guy-takes-big-med little-guy-apples-stock))
         (- (* putt-putt-takes-sma-big putt-putt-apples-stock) (* putt-putt-takes-big-sma putt-putt-apples-stock))
         (- (* putt-putt-takes-med-big putt-putt-apples-stock) (* putt-putt-takes-big-med putt-putt-apples-stock))))
    (= big-banana-imports
      (+ (- (* mega-rig-takes-sma-big mega-rig-banana-stock) (* mega-rig-takes-big-sma mega-rig-banana-stock))
         (- (* mega-rig-takes-med-big mega-rig-banana-stock) (* mega-rig-takes-big-med mega-rig-banana-stock))
         (- (* the-monster-takes-sma-big the-monster-banana-stock) (* the-monster-takes-big-sma the-monster-banana-stock))
         (- (* the-monster-takes-med-big the-monster-banana-stock) (* the-monster-takes-big-med the-monster-banana-stock))
         (- (* big-bertha-takes-sma-big big-bertha-banana-stock) (* big-bertha-takes-big-sma big-bertha-banana-stock))
         (- (* big-bertha-takes-med-big big-bertha-banana-stock) (* big-bertha-takes-big-med big-bertha-banana-stock))
         (- (* keep-truckin-takes-sma-big keep-truckin-banana-stock) (* keep-truckin-takes-big-sma keep-truckin-banana-stock))
         (- (* keep-truckin-takes-med-big keep-truckin-banana-stock) (* keep-truckin-takes-big-med keep-truckin-banana-stock))
         (- (* lonely-road-takes-sma-big lonely-road-banana-stock) (* lonely-road-takes-big-sma lonely-road-banana-stock))
         (- (* lonely-road-takes-med-big lonely-road-banana-stock) (* lonely-road-takes-big-med lonely-road-banana-stock))
         (- (* dusty-trail-takes-sma-big dusty-trail-banana-stock) (* dusty-trail-takes-big-sma dusty-trail-banana-stock))
         (- (* dusty-trail-takes-med-big dusty-trail-banana-stock) (* dusty-trail-takes-big-med dusty-trail-banana-stock))
         (- (* little-guy-takes-sma-big little-guy-banana-stock) (* little-guy-takes-big-sma little-guy-banana-stock))
         (- (* little-guy-takes-med-big little-guy-banana-stock) (* little-guy-takes-big-med little-guy-banana-stock))
         (- (* putt-putt-takes-sma-big putt-putt-banana-stock) (* putt-putt-takes-big-sma putt-putt-banana-stock))
         (- (* putt-putt-takes-med-big putt-putt-banana-stock) (* putt-putt-takes-big-med putt-putt-banana-stock))))
    (= big-orange-imports
      (+ (- (* mega-rig-takes-sma-big mega-rig-orange-stock) (* mega-rig-takes-big-sma mega-rig-orange-stock))
         (- (* mega-rig-takes-med-big mega-rig-orange-stock) (* mega-rig-takes-big-med mega-rig-orange-stock))
         (- (* the-monster-takes-sma-big the-monster-orange-stock) (* the-monster-takes-big-sma the-monster-orange-stock))
         (- (* the-monster-takes-med-big the-monster-orange-stock) (* the-monster-takes-big-med the-monster-orange-stock))
         (- (* big-bertha-takes-sma-big big-bertha-orange-stock) (* big-bertha-takes-big-sma big-bertha-orange-stock))
         (- (* big-bertha-takes-med-big big-bertha-orange-stock) (* big-bertha-takes-big-med big-bertha-orange-stock))
         (- (* keep-truckin-takes-sma-big keep-truckin-orange-stock) (* keep-truckin-takes-big-sma keep-truckin-orange-stock))
         (- (* keep-truckin-takes-med-big keep-truckin-orange-stock) (* keep-truckin-takes-big-med keep-truckin-orange-stock))
         (- (* lonely-road-takes-sma-big lonely-road-orange-stock) (* lonely-road-takes-big-sma lonely-road-orange-stock))
         (- (* lonely-road-takes-med-big lonely-road-orange-stock) (* lonely-road-takes-big-med lonely-road-orange-stock))
         (- (* dusty-trail-takes-sma-big dusty-trail-orange-stock) (* dusty-trail-takes-big-sma dusty-trail-orange-stock))
         (- (* dusty-trail-takes-med-big dusty-trail-orange-stock) (* dusty-trail-takes-big-med dusty-trail-orange-stock))
         (- (* little-guy-takes-sma-big little-guy-orange-stock) (* little-guy-takes-big-sma little-guy-orange-stock))
         (- (* little-guy-takes-med-big little-guy-orange-stock) (* little-guy-takes-big-med little-guy-orange-stock))
         (- (* putt-putt-takes-sma-big putt-putt-orange-stock) (* putt-putt-takes-big-sma putt-putt-orange-stock))
         (- (* putt-putt-takes-med-big putt-putt-orange-stock) (* putt-putt-takes-big-med putt-putt-orange-stock))))
    (= big-grapes-imports
      (+ (- (* mega-rig-takes-sma-big mega-rig-grapes-stock) (* mega-rig-takes-big-sma mega-rig-grapes-stock))
         (- (* mega-rig-takes-med-big mega-rig-grapes-stock) (* mega-rig-takes-big-med mega-rig-grapes-stock))
         (- (* the-monster-takes-sma-big the-monster-grapes-stock) (* the-monster-takes-big-sma the-monster-grapes-stock))
         (- (* the-monster-takes-med-big the-monster-grapes-stock) (* the-monster-takes-big-med the-monster-grapes-stock))
         (- (* big-bertha-takes-sma-big big-bertha-grapes-stock) (* big-bertha-takes-big-sma big-bertha-grapes-stock))
         (- (* big-bertha-takes-med-big big-bertha-grapes-stock) (* big-bertha-takes-big-med big-bertha-grapes-stock))
         (- (* keep-truckin-takes-sma-big keep-truckin-grapes-stock) (* keep-truckin-takes-big-sma keep-truckin-grapes-stock))
         (- (* keep-truckin-takes-med-big keep-truckin-grapes-stock) (* keep-truckin-takes-big-med keep-truckin-grapes-stock))
         (- (* lonely-road-takes-sma-big lonely-road-grapes-stock) (* lonely-road-takes-big-sma lonely-road-grapes-stock))
         (- (* lonely-road-takes-med-big lonely-road-grapes-stock) (* lonely-road-takes-big-med lonely-road-grapes-stock))
         (- (* dusty-trail-takes-sma-big dusty-trail-grapes-stock) (* dusty-trail-takes-big-sma dusty-trail-grapes-stock))
         (- (* dusty-trail-takes-med-big dusty-trail-grapes-stock) (* dusty-trail-takes-big-med dusty-trail-grapes-stock))
         (- (* little-guy-takes-sma-big little-guy-grapes-stock) (* little-guy-takes-big-sma little-guy-grapes-stock))
         (- (* little-guy-takes-med-big little-guy-grapes-stock) (* little-guy-takes-big-med little-guy-grapes-stock))
         (- (* putt-putt-takes-sma-big putt-putt-grapes-stock) (* putt-putt-takes-big-sma putt-putt-grapes-stock))
         (- (* putt-putt-takes-med-big putt-putt-grapes-stock) (* putt-putt-takes-big-med putt-putt-grapes-stock))))
    (= now-apples-imports
      (+ (- (* mega-rig-takes-sma-now mega-rig-apples-stock) (* mega-rig-takes-now-sma mega-rig-apples-stock))
         (- (* the-monster-takes-sma-now the-monster-apples-stock) (* the-monster-takes-now-sma the-monster-apples-stock))
         (- (* big-bertha-takes-sma-now big-bertha-apples-stock) (* big-bertha-takes-now-sma big-bertha-apples-stock))
         (- (* keep-truckin-takes-sma-now keep-truckin-apples-stock) (* keep-truckin-takes-now-sma keep-truckin-apples-stock))
         (- (* lonely-road-takes-sma-now lonely-road-apples-stock) (* lonely-road-takes-now-sma lonely-road-apples-stock))
         (- (* dusty-trail-takes-sma-now dusty-trail-apples-stock) (* dusty-trail-takes-now-sma dusty-trail-apples-stock))
         (- (* little-guy-takes-sma-now little-guy-apples-stock) (* little-guy-takes-now-sma little-guy-apples-stock))
         (- (* putt-putt-takes-sma-now putt-putt-apples-stock) (* putt-putt-takes-now-sma putt-putt-apples-stock))))
    (= now-banana-imports
      (+ (- (* mega-rig-takes-sma-now mega-rig-banana-stock) (* mega-rig-takes-now-sma mega-rig-banana-stock))
         (- (* the-monster-takes-sma-now the-monster-banana-stock) (* the-monster-takes-now-sma the-monster-banana-stock))
         (- (* big-bertha-takes-sma-now big-bertha-banana-stock) (* big-bertha-takes-now-sma big-bertha-banana-stock))
         (- (* keep-truckin-takes-sma-now keep-truckin-banana-stock) (* keep-truckin-takes-now-sma keep-truckin-banana-stock))
         (- (* lonely-road-takes-sma-now lonely-road-banana-stock) (* lonely-road-takes-now-sma lonely-road-banana-stock))
         (- (* dusty-trail-takes-sma-now dusty-trail-banana-stock) (* dusty-trail-takes-now-sma dusty-trail-banana-stock))
         (- (* little-guy-takes-sma-now little-guy-banana-stock) (* little-guy-takes-now-sma little-guy-banana-stock))
         (- (* putt-putt-takes-sma-now putt-putt-banana-stock) (* putt-putt-takes-now-sma putt-putt-banana-stock))))
    (= now-orange-imports
      (+ (- (* mega-rig-takes-sma-now mega-rig-orange-stock) (* mega-rig-takes-now-sma mega-rig-orange-stock))
         (- (* the-monster-takes-sma-now the-monster-orange-stock) (* the-monster-takes-now-sma the-monster-orange-stock))
         (- (* big-bertha-takes-sma-now big-bertha-orange-stock) (* big-bertha-takes-now-sma big-bertha-orange-stock))
         (- (* keep-truckin-takes-sma-now keep-truckin-orange-stock) (* keep-truckin-takes-now-sma keep-truckin-orange-stock))
         (- (* lonely-road-takes-sma-now lonely-road-orange-stock) (* lonely-road-takes-now-sma lonely-road-orange-stock))
         (- (* dusty-trail-takes-sma-now dusty-trail-orange-stock) (* dusty-trail-takes-now-sma dusty-trail-orange-stock))
         (- (* little-guy-takes-sma-now little-guy-orange-stock) (* little-guy-takes-now-sma little-guy-orange-stock))
         (- (* putt-putt-takes-sma-now putt-putt-orange-stock) (* putt-putt-takes-now-sma putt-putt-orange-stock))))
    (= now-grapes-imports
      (+ (- (* mega-rig-takes-sma-now mega-rig-grapes-stock) (* mega-rig-takes-now-sma mega-rig-grapes-stock))
         (- (* the-monster-takes-sma-now the-monster-grapes-stock) (* the-monster-takes-now-sma the-monster-grapes-stock))
         (- (* big-bertha-takes-sma-now big-bertha-grapes-stock) (* big-bertha-takes-now-sma big-bertha-grapes-stock))
         (- (* keep-truckin-takes-sma-now keep-truckin-grapes-stock) (* keep-truckin-takes-now-sma keep-truckin-grapes-stock))
         (- (* lonely-road-takes-sma-now lonely-road-grapes-stock) (* lonely-road-takes-now-sma lonely-road-grapes-stock))
         (- (* dusty-trail-takes-sma-now dusty-trail-grapes-stock) (* dusty-trail-takes-now-sma dusty-trail-grapes-stock))
         (- (* little-guy-takes-sma-now little-guy-grapes-stock) (* little-guy-takes-now-sma little-guy-grapes-stock))
         (- (* putt-putt-takes-sma-now putt-putt-grapes-stock) (* putt-putt-takes-now-sma putt-putt-grapes-stock))))

    (= sma-apples-supply (+ sma-apples-stock sma-apples-imports))
    (= sma-banana-supply (+ sma-banana-stock sma-banana-imports))
    (= sma-orange-supply (+ sma-orange-stock sma-orange-imports))
    (= sma-grapes-supply (+ sma-grapes-stock sma-grapes-imports))
    (= med-apples-supply (+ med-apples-stock med-apples-imports))
    (= med-banana-supply (+ med-banana-stock med-banana-imports))
    (= med-orange-supply (+ med-orange-stock med-orange-imports))
    (= med-grapes-supply (+ med-grapes-stock med-grapes-imports))
    (= big-apples-supply (+ big-apples-stock big-apples-imports))
    (= big-banana-supply (+ big-banana-stock big-banana-imports))
    (= big-orange-supply (+ big-orange-stock big-orange-imports))
    (= big-grapes-supply (+ big-grapes-stock big-grapes-imports))
    (= now-apples-supply (+ now-apples-stock now-apples-imports))
    (= now-banana-supply (+ now-banana-stock now-banana-imports))
    (= now-orange-supply (+ now-orange-stock now-orange-imports))
    (= now-grapes-supply (+ now-grapes-stock now-grapes-imports))

    (= sma-cost (* sma-has-warehouse city-smallville-cost))
    (= med-cost (* med-has-warehouse city-mediumville-cost))
    (= big-cost (* big-has-warehouse city-bigville-cost))
    (= now-cost (* now-has-warehouse city-nowheresville-cost))

    (<= sma-apples-supply city-smallville-apples)
    (<= sma-banana-supply city-smallville-banana)
    (<= sma-orange-supply city-smallville-orange)
    (<= sma-grapes-supply city-smallville-grapes)
    (<= med-apples-supply city-mediumville-apples)
    (<= med-banana-supply city-mediumville-banana)
    (<= med-orange-supply city-mediumville-orange)
    (<= med-grapes-supply city-mediumville-grapes)
    (<= big-apples-supply city-bigville-apples)
    (<= big-banana-supply city-bigville-banana)
    (<= big-orange-supply city-bigville-orange)
    (<= big-grapes-supply city-bigville-grapes)
    (<= now-apples-supply city-nowheresville-apples)
    (<= now-banana-supply city-nowheresville-banana)
    (<= now-orange-supply city-nowheresville-orange)
    (<= now-grapes-supply city-nowheresville-grapes)

    (= sma-profit
       (+ (.* product-apples-profit sma-apples-supply)
          (.* product-banana-profit sma-banana-supply)
          (.* product-orange-profit sma-orange-supply)
          (.* product-grapes-profit sma-grapes-supply)))
    (= med-profit
       (+ (.* product-apples-profit med-apples-supply)
          (.* product-banana-profit med-banana-supply)
          (.* product-orange-profit med-orange-supply)
          (.* product-grapes-profit med-grapes-supply)))
    (= big-profit
       (+ (.* product-apples-profit big-apples-supply)
          (.* product-banana-profit big-banana-supply)
          (.* product-orange-profit big-orange-supply)
          (.* product-grapes-profit big-grapes-supply)))
    (= now-profit
       (+ (.* product-apples-profit now-apples-supply)
          (.* product-banana-profit now-banana-supply)
          (.* product-orange-profit now-orange-supply)
          (.* product-grapes-profit now-grapes-supply)))

    (= profit
       (- (+ sma-profit
             med-profit
             big-profit
             now-profit)
          (+ sma-cost
             med-cost
             big-cost
             now-cost)
          (+ mega-rig-cost
             the-monster-cost
             big-bertha-cost
             keep-truckin-cost
             lonely-road-cost
             dusty-trail-cost
             little-guy-cost
             putt-putt-cost)))))
